
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDNXETY9fDSucXhdlxV8agwcwdoNjVo8',
    appId: '1:865707638760:ios:ab93a05c6b226f78006e5d',
    messagingSenderId: '865707638760',
    projectId: 'cargo-delivery-app-4fbb8',
    storageBucket: 'cargo-delivery-app-4fbb8.firebasestorage.app',
    androidClientId: '865707638760-s0aqpc046e91dpjeue2j1qq5f7aleu90.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaDNXETY9fDSucXhdlxV8agwcwdoNjVo8',
    appId: '1:865707638760:ios:ab93a05c6b226f78006e5d',
    messagingSenderId: '865707638760',
    projectId: 'cargo-delivery-app-4fbb8',
    storageBucket: 'cargo-delivery-app-4fbb8.firebasestorage.app',
    androidClientId: '865707638760-s0aqpc046e91dpjeue2j1qq5f7aleu90.apps.googleusercontent.com',
    iosClientId: '865707638760-dsuokffqtdnmspi791qel8cgv1rtcr9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargoDriverApp.RunnerTests',
  );

}